### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by VorpalBlade** [zeenix/xdg-home#3]
Hi!

This crate is one reason why I'm currently getting two separate versions of the nix crate compiled into my binary. I would like to reduce the number of dependencies that I have in multiple versions, in order to reduce the binary size.

I see you have already upgraded to a newer dependency on nix, but not yet made a release. It would be awesome if you could make a new release soon.

**Comment by zeenix** [comment]
https://toot.cat/@zbus/111126407295058295
